# Generated by Django 5.2.5 on 2025-08-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('جيد', 'جيد'), ('جيد جداً', 'جيد جداً'), ('ممتاز', 'ممتاز')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'unique_together': {('student', 'page_number', 'date')},
            },
        ),
    ]
